# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulb',
            name='consumption',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bulb',
            name='brightness',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bulb',
            name='bulb_type',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bulb',
            name='rgbColor',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
