# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lights', '0002_auto_20171201_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulb',
            name='rgbColor',
            field=models.CharField(blank=True, default='ffcc00', max_length=6, null=True),
        ),
    ]
