# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lights', '0004_auto_20171201_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulb',
            name='rgbColor',
            field=models.CharField(blank=True, default='ffcc00', max_length=8, null=True),
        ),
    ]
